name: build windows

on:
  pull_request:
  push:

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os:
          - windows-latest
        ocaml-compiler:
          - "4.14"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
        
      - name: Set opam repository url
        id: repository
        shell: bash
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            echo "::set-output name=url::https://github.com/ocaml-opam/opam-repository-mingw.git#sunset"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            echo "::set-output name=url::https://github.com/custom/opam-repository.git#macOS"
          else
            echo "::set-output name=url::https://github.com/ocaml/opam-repository.git"
          fi
    
      - name: Set-up OCaml with repository ${{ steps.repository.outputs.url }}
        uses: ocaml/setup-ocaml@v2
        with:
          opam-repositories: |
            default: ${{ steps.repository.outputs.url }}

      # - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
      #   uses: ocaml/setup-ocaml@v2
      #   with:
      #     ocaml-compiler: ${{ matrix.ocaml-compiler }}
      
      - name: opam install dependency
        run: opam install menhir
      
      - name: dune build
        run: opam exec -- dune build --verbose
      
      - name: make tarball 
        run: |
          cp -arL _build/install/default . 
          mv default lc
          tar -czvf tarball.tar.gz lc
          rm default -rf

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tarball
          path: tarball.tar.gz
