name: build Linux and Windows binary based on Linux

on:
  CI:
    workflows:
      - check
    types: 
      - completed
  # pull_request:
  # push:

permissions: read-all

jobs:
  build_Linux_bin:
    if: ${{ github.event.CI.conclusion == 'success' }}
    if: ${{ github.event.CI.strategy.matrix.ocaml-compiler }} == "4.14"

    steps:
      - name: opam install windows cross compiler
        run: | 
          sudo apt install gcc-mingw-w64-x86-64 -y
          opam repository add windows https://github.com/ocaml-cross/opam-cross-windows.git
          opam install ocaml-windows -y

      - name: opam install dependency
        run: opam install menhir -y

      - name: dune build linux
        run: |
          cp -a dune-linux dune
          opam exec -- dune build --verbose

      - name: move linux binary
        run: |
          cp -a -r -L _build/default/main.exe . 
          mv main.exe lc

      - name: upload linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: lc
          path: lc          

      - name: dune build windows
        run: |
          cp -a dune-windows dune
          opam exec -- dune build -x windows --verbose          

      - name: move windows binary 
        run: |
          cp -a -r -L _build/default.windows/main.exe . 
          mv main.exe lc.exe

      - name: upload windows artifact
        uses: actions/upload-artifact@v3
        with:
          name: lc.exe
          path: lc.exe
